### ISSUE TITLE
Scaffold a TripJoinRequest entity

### ISSUE THREAD

**Issue by jonnyjava** [andresgarcia20/shatit#27]
- only a passenger can request to join a trip
- in the form the passenger can specify how many people will onboard. (we need validation to ensure there are enough seats available, the UI need to show the available seats accordingly) 
- in the form there will be a checkbox for pets, luggage and kids (specifying the age)
- the request has different stages: requested, accepted, payment_in_progress, paid, booked, rejected, cancelled. 
- add some validations for stage changes; for example a user cannot have 2 trips in approved status with the same date.
- automatically whenever a request gets accepted, all the others covering the same date will be rejected

**Comment by andresgarcia20** [comment]
TODO: save more than one value in the array for TripJoinRequest and Trip models
